"""
dazzle-checksum.py - Cross-Platform Checksum Tool

A comprehensive tool for generating folder-specific checksum files (.shasum) that enables
data integrity verification across different machines and operating systems.

Features:
- Cross-platform compatibility (Windows, macOS, Linux, BSD)
- FIFO directory processing for memory efficiency
- Native tool integration with Python fallback
- Line ending normalization for consistent checksums
- Symlink/junction loop detection
- Incremental updates and change tracking
- Compatible output format with standard tools
- Monolithic checksum files for entire directory trees

Usage:
    dazzle-checksum.py [OPTIONS] [DIRECTORY]

Examples:
    dazzle-checksum.py                           # Current directory
    dazzle-checksum.py --recursive /path/to/dir  # Recursive processing
    dazzle-checksum.py --algorithm sha512        # Different algorithm
    dazzle-checksum.py --verify                  # Verify existing checksums
    dazzle-checksum.py --update                  # Incremental update
    dazzle-checksum.py --monolithic --recursive  # Single checksum file for tree
    dazzle-checksum.py --monolithic --output checksums.sha256  # Custom output

This package is the src/ split of the former single-file dazzlesum.py
(Phase 1 of the src/ refactor); the repo-root dazzlesum.py is now a
stitched build artifact generated by scripts/build_monolith.py. This
__init__ re-exports the monolith's public surface so ``import dazzlesum``
keeps working unchanged.
"""

from ._version import (  # noqa: F401
    MAJOR,
    MINOR,
    PATCH,
    PHASE,
    PRE_RELEASE_NUM,
    __author__,
    __version__,
    get_package_version,
)
from .constants import (  # noqa: F401
    CACHE_FILENAME,
    DEFAULT_ALGORITHM,
    DEFAULT_CHUNK_SIZE,
    HAVE_UNCTOOLS,
    MONOLITHIC_DEFAULT_NAME,
    SHASUM_FILENAME,
    STATE_FILENAME,
    SUPPORTED_ALGORITHMS,
    file_exists,
    is_unc_path,
    is_windows,
    logger,
    safe_open,
)
from . import state  # noqa: F401
from .output import (  # noqa: F401
    ColorFormatter,
    DazzleLogger,
    VerbosityConfig,
    initialize_squelch_from_verbosity,
    setup_logging,
)
from .patterns import (  # noqa: F401
    CompiledPatternMatcher,
    _always_excluded_name,
    _should_include_file_simple,
)
from .results import (  # noqa: F401
    GrandTotals,
    ProgressTracker,
    SummaryCollector,
    calculate_verification_status,
    format_status_with_colors,
)
from .hashing import (  # noqa: F401
    DazzleHashCalculator,
    LineEndingHandler,
)
from .walk import (  # noqa: F401
    FIFODirectoryWalker,
    SymlinkHandler,
    count_dirs_and_files,
)
from .manifest import (  # noqa: F401
    MonolithicWriter,
    ShasumManager,
    is_monolithic_file,
    parse_shasum_file,
)
from .shadow import ShadowPathResolver  # noqa: F401
from .statecache import StateCache  # noqa: F401
from .engine import ChecksumGenerator  # noqa: F401
from .cli import (  # noqa: F401
    DetailedHelpAction,
    VerbosityHelpAction,
    auto_detect_checksum_file,
    create_argument_parser,
    create_parent_parser,
    detect_context_command,
    execute_create_action,
    execute_main_action,
    execute_manage_action,
    execute_update_action,
    execute_verify_action,
    get_examples_help,
    get_mode_help,
    get_shadow_help,
    main,
    show_detailed_help,
    show_verbosity_help,
)
