"""Select which dazzlesum implementation the in-process tests import.

Since the Phase 1 src/ split, TWO import targets exist:

* the package at src/dazzlesum/ (source of truth), and
* the stitched single-file artifact at the repo root, dazzlesum.py
  (generated by scripts/build_monolith.py).

Test modules do ``sys.path.insert(0, repo_root); import dazzlesum``, which
naturally resolves the repo-root artifact. To exercise the PACKAGE instead,
this conftest (imported by pytest before any test module) pre-imports the
package from src/ so ``sys.modules['dazzlesum']`` is already settled by the
time test modules import it.

    DAZZLESUM_TEST_TARGET=package   (default) in-process tests use src/dazzlesum
    DAZZLESUM_TEST_TARGET=stitched  in-process tests use the root dazzlesum.py

Subprocess-based CLI tests always execute the repo-root dazzlesum.py
regardless of this setting, so a default run covers the package (in-process)
AND the stitched artifact (subprocess) in one pass.
"""

import importlib.util
import os
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_TARGET = os.environ.get('DAZZLESUM_TEST_TARGET', 'package')


class _PinDazzlesumToSrc:
    """Meta-path finder pinning 'dazzlesum' to the src/ package.

    sys.path order is NOT enough: test modules insert the repo root at
    position 0, and importlib.reload() re-resolves top-level modules through
    sys.path -- so a reload mid-test would silently flip from the package to
    the root stitched artifact (whose embedded version stamp can legitimately
    differ by one build count). A meta-path entry outranks all path-based
    resolution, making initial import AND reload deterministic.
    """

    def find_spec(self, name, path=None, target=None):
        if name == 'dazzlesum':
            pkg = _REPO_ROOT / 'src' / 'dazzlesum'
            return importlib.util.spec_from_file_location(
                'dazzlesum', pkg / '__init__.py',
                submodule_search_locations=[str(pkg)])
        return None


if _TARGET == 'package':
    sys.path.insert(0, str(_REPO_ROOT / 'src'))
    sys.meta_path.insert(0, _PinDazzlesumToSrc())
    import dazzlesum  # noqa: F401  (cache the package in sys.modules)
elif _TARGET != 'stitched':
    raise RuntimeError(
        f"DAZZLESUM_TEST_TARGET must be 'package' or 'stitched', got {_TARGET!r}")
